### PR TITLE
Use collections.abc

### PR DESCRIPTION
**Pull request by YoYoost**
Use collections.abc

### CODE REVIEW

**Comment by YoYoost** [comment]
Hi, I tested this using the HomeAssistant integration.

**Comment by jcconnell** [comment]
Interesting - so the motivation for this is the deprecation warning?

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Comment by YoYoost** [comment]
Well this wrapper is used in the HomeAssistant integration https://www.home-assistant.io/integrations/magicseaweed/ . This integration broke hence https://github.com/home-assistant/core/issues/74731 was opened and I tried to find a fix. While researching the error I found that deprecation and one of the suggestions was to use collections.abc instead of collections. I tried using a more specific 'try, except' solution to only import the use of 'MutableMapping' but that also threw errors.

This PR makes the integration work again on python 3.10 but I am not knowledgeable enough to know\predict how long the workaround keeps working.

**Comment by jcconnell** [comment]
Credit to you for bringing this to my attention! Thanks again. 

Working on a resolution in #5. I opted to use `flatten_json` from the flatten library instead. Let me know your thoughts. I'll probably close this PR when that is merged in.

**Comment by YoYoost** [comment]
That is probably a more future proof and more elegant solution, looks good to me!

**Comment by jcconnell** [comment]
Closing since this was fixed in 1.0.6

**Pull request closed without merging**
